-- The audit log behind /admin/activity and the Overview panel.
--
-- This table predates the sql/ directory and was created by hand, so the
-- create below is a `if not exists` no-op on an existing install. What is new
-- is the `mailbox` column at the bottom — re-run this file to pick it up.

create table if not exists public.admin_activity (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  -- Who did it, by email. Rendered as a display name by looking the address up
  -- in `admins` at read time rather than denormalising the name here, so a
  -- rename corrects the whole history instead of only what happens next.
  actor      text        not null,
  action     text        not null,
  target     text,

  -- Groups entries in the UI: Signup, Inbox, Access, Email, System.
  kind       text        not null default 'System'
);

-- Which mailbox the entry is about, for Email entries only; null everywhere
-- else. Mail is scoped to the admin who holds the address, and without this the
-- log would hand every admin the subject lines and correspondents of mailboxes
-- they cannot open — the message list would be private and the audit trail
-- beside it would not.
--
-- Not a reference to `mailboxes`: deleting an address must not erase the entry
-- recording that it was deleted.
alter table public.admin_activity add column if not exists mailbox text;

create index if not exists admin_activity_created_at_idx
  on public.admin_activity (created_at desc);

-- Same posture as every other table: RLS on with no policies, so the anon key
-- reaches nothing. Only the service role, behind requireAdmin(), reads it.
alter table public.admin_activity enable row level security;
